### ISSUE TITLE
"clerk_key_invalid"

### ISSUE THREAD

**Issue by roninio** [clerk/clerk-sdk-python#26]
Hi

trying to use the api geting 
clerk_backend_api.models.clerkerrors.ClerkErrors: {"errors":[{"code":"clerk_key_invalid","long_message":"The provided Clerk Secret Key is invalid. Make sure that your Clerk Secret Key is correct.","message":"The provided Clerk Secret Key is invalid. Make sure that your Clerk Secret Key is correct."}]}

Is there a proper example where or how to set the secret key? 

Thanks

**Comment by jim-at-jibba** [comment]
I am getting the same error. 

I am trying to update update public meta data but getting the same response

```
        s = Clerk(
            bearer_auth=credentials.credentials,
        )
        res = s.users.update_metadata(
            user_id=token_data.sub,
            request_body={
                "public_metadata": {
                    "onboadingComplete": True,
                },
            },
        )
```

**Comment by jim-at-jibba** [comment]
@roninio I figured it out. Its just a poorly named property. Its not the bearer_auth token its the api key available from the dashboard.

Hope that helps
