### ISSUE TITLE
Missing `authenticate_request` type

### ISSUE THREAD

**Issue by targetlucked69** [clerk/clerk-sdk-python#50]
![Screenshot 2024-11-04 at 11 12 47 PM](https://github.com/user-attachments/assets/58b7683d-9d19-47ac-9d57-212ddfccc4e0)

![Screenshot 2024-11-04 at 11 13 36 PM](https://github.com/user-attachments/assets/e4384cb3-25dd-4fd2-adb9-e52fb77f9da7)

**Comment by 2ynn** [comment]
@targetlucked69 the `authenticate_request()` method is not part of the SDK per se, it is a [helper function](https://github.com/clerk/clerk-sdk-python/blob/c7d06ca0291210616dc113aca7bf759ee93997c9/src/clerk_backend_api/jwks_helpers/authenticaterequest.py#L72) that is [dynamically attached](https://github.com/clerk/clerk-sdk-python/blob/c7d06ca0291210616dc113aca7bf759ee93997c9/src/clerk_backend_api/jwks_helpers/__init__.py#L30) to the sdk class for convenience, so I think this explains why your lsp is not picking it up.
